apiVersion: v2
type: application
name: dex-k8s-authenticator
version: 0.0.1
appVersion: "1.4.0"
kubeVersion: ">=1.14.0-0"
description: A helper web-app which talks to one or more Dex Identity services to generate kubectl commands for creating and modifying a kubeconfig.
icon: https://dexidp.io/favicon.png
keywords:
  - oidc
  - dex
  - kubernetes
  - k8s
home: https://github.com/mintel/dex-k8s-authenticator
sources:
  - https://github.com/mintel/dex-k8s-authenticator
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/dex-k8s-authenticator
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - Add license file
  artifacthub.io/images: |
    - name: dex-k8s-authenticator
      image: mintel/dex-k8s-authenticator:1.4.0
