apiVersion: v2
type: application
name: caddy
version: 0.0.12
appVersion: "2.3.0"
kubeVersion: ">=1.16.0-0"
description: A powerful, enterprise-ready, open source web server with automatic HTTPS written in Go.
icon: https://caddyserver.com/resources/images/favicon.png
keywords:
  - http
  - https
  - web
  - server
home: https://caddyserver.com/
sources:
  - https://github.com/caddyserver/caddy
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/caddy
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - Fix ingress template
  artifacthub.io/images: |
    - name: caddy
      image: caddy:2.3.0
