apiVersion: v2
type: application
name: sftpgo
version: 0.0.8
appVersion: 1.2.2
description: Fully featured and highly configurable SFTP server with optional FTP/S and WebDAV support.
keywords:
  - sftp
  - ftp
  - webdav
home: https://github.com/drakkan/sftpgo
sources:
  - https://github.com/drakkan/sftpgo
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - Updated SFTPGo to 1.2.2
  artifacthub.io/images: |
    - name: sftpgo
      image: ghcr.io/drakkan/sftpgo:v1.2.2
    - name: sftpgo-alpine
      image: ghcr.io/drakkan/sftpgo:v1.2.2-alpine
  artifacthub.io/maintainers: |
    - name: sagikazarmark
      email: mark.sagikazar@gmail.com
