apiVersion: v2
type: application
name: sftpgo
version: 0.8.0
appVersion: 2.1.0
kubeVersion: ">=1.16.0-0"
description: Fully featured and highly configurable SFTP server with optional FTP/S and WebDAV support.
keywords:
  - sftp
  - ftp
  - webdav
home: https://github.com/drakkan/sftpgo
sources:
  - https://github.com/drakkan/sftpgo
  - https://github.com/sagikazarmark/helm-charts/tree/master/charts/sftpgo
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated documentation
  artifacthub.io/images: |
    - name: sftpgo
      image: ghcr.io/drakkan/sftpgo:v2.1.0
    - name: sftpgo-alpine
      image: ghcr.io/drakkan/sftpgo:v2.1.0-alpine
